name: Builds the app

run-name: This is the test run-name

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
      - uses: actions/checkout@v3
      - run: echo "Branch name is $GITHUB_REF_NAME or $GITHUB_REF"
      
