name: Deploys the app to staging

run-name: Deploying the app to staging...

on:
  workflow_dispatch:
    branches:
      - release/*

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: staging
    steps:
      - uses: actions/checkout@v3

      - name: show_branch_name
        run: echo "Branch name is $GITHUB_REF_NAME or $GITHUB_REF"
